config/routes.rb
Blog::Application.routes.draw do

  resources :posts, :users

  root to: "home#index"
  get "home/index"

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :name, :title  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :status
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(name: params[:name], title: params[:title], content: params[:content])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(title: params[:title], content: params[:content])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    respond_to do |format|
      format.html #index.html.erb
      format.json {render :json => @users}
    end
  end

  def get_users
    @users = User.all
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(name: params[:name], status: params[:status])

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "index" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @user = User.find(params[:id])
    respond_to do |format|
      format.html #index.html.erb
      format.json {render :json => @users}
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update_attributes(name: params[:name], status: params[:status])
        format.html { redirect_to @user, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "show" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    respond_to do |format|
      format.html {redirect_to users_url} #index.html.erb
      format.json {render :json => @users}
    end
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div id="content">
  <div class="jumbotron">
   <h1>Welcome to abdel23's plateform</h1>
   <p class="lead">
     <img src="https://robohash.org/abdel23" alt="I'm Yeoman"><br>
     This is Abdel23's robot avatar
   </p>
   <p><a class="btn btn-lg btn-success" ng-href="#/">Splendid!<span class="glyphicon glyphicon-ok"></span></a></p>
  </div>

 <div class="row marketing">
   <h4>Abdel23</h4>
   <p>One of the greatest Pes2006 and Pes2011 players of all time
   </p>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Exemple User Interface</title>

    <!-- Bootstrap core CSS -->
    <link href="../../dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <link href="../../assets/css/ie10-viewport-bug-workaround.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="jumbotron.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>
    <script type = "text/javascript"
         src = "http://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js">
    </script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Test Blog</a>
          <a class="navbar-brand" href=<%="#{users_path}"%>>Users</a>
          <a class="navbar-brand" href=<%="#{posts_path}"%>>Posts</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav>


<%= yield %>

<footer>
  <p>&copy; 2015 Company, Inc.</p>
</footer>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
</body>
</html>

app/views/posts/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
       <p class="lead">
        <img src="https://robohash.org/abdel23" alt="I'm abdel23"><br>
       </p>
       <p><a class="btn btn-lg btn-success" ng-href="#/">Splendid!<span class="glyphicon glyphicon-ok"></span></a></p>
       <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
         New post
       </button>
    </div>
    <div class="row">
      <h1>This is the posts page</h1>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">New post</h4>
      </div>
      <form id="post-form" >
        <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Username:</label>
            <input type="text" class="form-control" name="name">
          </div>
          <div class="form-group">
            <label for="recipient-title" class="control-label">Title:</label>
            <input type="text" class="form-control" name="title">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Content:</label>
            <textarea class="form-control" name="content"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" value="SUBMIT" class="btn btn-primary" >Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div>


<table>
  <% @posts.each do |post| %>
    <tr>
      <td>
        <a><img src=<%="https://robohash.org/#{post.name}"%> class="img-circle" alt="I'm Yeoman"><br></a>
        <a class="btn btn-lg btn-success"><%=post.name%><span class="glyphicon glyphicon-ok"></span></a>
      </td>
      <td>
        <a><h1><%= post.title %></h1></a>
        <a><%= post.content %></a>
      </td>
      <td><a class="btn btn-default" href=<%="posts/#{post.id}"%> role="button">Show &raquo;</a></td>
      <td><%= link_to  "Delete", post, :class=>"btn btn-danger" , method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>


<script type="text/javascript" language = "javascript">
  $(function(){
    $('#post-form').on('submit', function(e){
        e.preventDefault();
        $.ajax({
            url: "posts", //this is the submit URL
            type: 'POST',
            data: $('#post-form').serializeArray(),
            dataType: "json",
            success: function(result){
                alert('successfully submitted')
                window.location.reload()
            }
        });
    });
  });
</script>

app/views/posts/show.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <div class="col-md-4">
      <p class="lead">
      <img src=<%="https://robohash.org/#{@post.name}"%> alt="I'm Yeoman"><br>
      </p>
      <p><a class="btn btn-lg btn-success" ng-href="#/"><%=@post.name%><span class="glyphicon glyphicon-ok"></span></a></p>
    </div>
    <div class="col-md-8">
      <h1><%= @post.title%></h1>
      <h2><%= @post.content %></h2>
      <tr>
        <p>
          <button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
                Edit
          </button>
          <a class="btn btn-primary btn-lg" href="<%=posts_path%>" role="button">Back &raquo;</a>
        </p>
      </tr>
    </div>
  </div>
</div>

<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Editing post ....</h4>
      </div>
      <form id="post-form">
        <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Title:</label>
            <input type="text" class="form-control" name="title" value="<%=@post.title%>">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Content:</label>
            <textarea class="form-control" name="content"><%=@post.content%></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" value="SUBMIT">Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div>


<script type="text/javascript" language = "javascript">
  $(function(){
    $('#post-form').on('submit', function(e){
        e.preventDefault();
        $.ajax({
            url: <%="#{@post.id}"%>, //this is the submit URL
            type: 'PUT',
            data: $('#post-form').serializeArray(),
            dataType: "json",
            success: function(result){
                 alert('successfully submitted')
                 window.location.reload()
            }
        });
    });
  });
</script>

app/views/users/index.html.erb
<div class="jumbotron">
  <div class="container">
    <div class="row">
      <p class="lead">
        <img src="https://robohash.org/abdel23" alt="I'm abdel23"><br>
      </p>
      <p><a class="btn btn-lg btn-success" ng-href="#/">Splendid!<span class="glyphicon glyphicon-ok"></span></a></p>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">New user</button>
    </div>
    <div class="row">
      <h1>This is the users page</h1>
    </div>
  </div>
</div>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">New user</h4>
      </div>
      <form id="user-form">
        <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Username:</label>
            <input type="text" class="form-control" name="name">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Status:</label>
            <textarea class="form-control" name="status"></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" value="SUBMIT" class="btn btn-primary" >Save</button>
        </div>
      </form>
    </div>
  </div>
</div>
    <!-- Main jumbotron for a primary marketing message or call to action -->

<div class="container">
  <!-- Example row of columns -->
  <% @users.each do |user| %>
      <div class="col-md-6">
        <div class="col-md-6">
          <p class="lead">
            <img src=<%="https://robohash.org/#{user.name}"%> alt="I'm Yeoman"><br>
          </p>
        </div>
        <div class="col-md-6">
          <h2><%= user.name %></h2>
          <p><%= user.status %></p>
          <p><a class="btn btn-default" href=<%="users/#{user.id}"%> role="button">Show &raquo;</a></p>
        </div>
      </div>
  <% end %>
</div> <!-- /container -->

<script type="text/javascript" language = "javascript">
  $(function(){
    $('#user-form').on('submit', function(e){
        e.preventDefault();
        $.ajax({
            url: "users", //this is the submit URL
            type: 'POST',
            data: $('#user-form').serializeArray(),
            dataType: "json",
            success: function(result){
                 alert('successfully submitted')
                 window.location.reload()
            }
        });
    });
  });
</script>

app/views/users/show.html.erb
<!--  -->

<div class="jumbotron">
  <div class="container">
    <div class="col-md-4">
      <p class="lead">
        <img src=<%="https://robohash.org/#{@user.name}"%> alt="I'm Yeoman"><br>
      </p>
      <p><a class="btn btn-lg btn-success" ng-href="#/">Splendid!<span class="glyphicon glyphicon-ok"></span></a></p>
    </div>
    <div class="col-md-8">
      <h1>Welcome to <%=@user.name%>'s profile</h1>
      <h2><%=@user.status %></h2>
      <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Edit Status</button>
    </div>
  </div>
</div>


<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="exampleModalLabel">Editing user ....</h4>
      </div>
      <form id="user-form">
        <div class="modal-body">
          <div class="form-group">
            <label for="recipient-name" class="control-label">Username:</label>
            <input type="text" class="form-control" name="name" value="<%=@user.name%>">
          </div>
          <div class="form-group">
            <label for="message-text" class="control-label">Status:</label>
            <textarea class="form-control" name="status"><%=@user.status%></textarea>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" value="SUBMIT" class="btn btn-primary" >Save</button>
        </div>
      </form>
    </div>
  </div>
</div>

<div class="container">
  <!-- Example row of columns -->
  <div class="row">
    <div class="col-md-4">
      <h2>First post</h2>
      <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
      <p><a class="btn btn-default" href="#" role="button">View details &raquo;</a></p>
    </div>
  </div>
</div>

<script type="text/javascript" language = "javascript">
  $(function(){
    $('#user-form').on('submit', function(e){
        e.preventDefault();
        $.ajax({
            url: <%="#{@user.id}"%>, //this is the submit URL
            type: 'PUT',
            data: $('#user-form').serializeArray(),
            dataType: "json",
            success: function(result){
                 alert('successfully submitted')
                 window.location.reload()
            }
        });
    });
  });
</script>